name: Laravel Testing

on:
  pull_request:

jobs:
  laravel-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Version
        run: docker version

      - name: Build Dcker Image
        run: docker compose build

      - name: Create & Start Docker Container
        run: docker compose up -d

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            docker compose exec -T app php -r 'try { new PDO("mysql:host=db;dbname=laravel", "phper", "secret"); exit(0); } catch (Exception $e) { echo "Waiting for DB...\n"; sleep(2); }'
          done
      - name: OS Version
        run:  |
          docker compose exec -T app cat /etc/os-release
          docker compose exec -T app cat /etc/debian_version

      - name: PHP Version
        run: docker compose exec -T app php --version

      - name: Composer Version
        run: docker compose exec -T app composer --version

      - name: Install Dependencies
        run: docker compose exec -T app composer install

      - name: Laravel Setting
        run: |
          docker compose exec -T app cp .env.example .env
          docker compose exec -T app php artisan config:clear
          docker compose exec -T app php artisan key:generate

      - name: Laravel Migration Testing
        run: docker compose exec -T app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker compose exec -T app php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker compose exec -T app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker compose exec -T app php artisan test
